project:
  type: website
  output-dir: docs

website:
  title: "DACSS758 Text as Data Fall 2024"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Tutorial1.qmd
        text: Tutorial1
      - href: Tutorial2.qmd
        text: Tutorial2
      




format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



