project:
  type: website
  output-dir: docs

website:
  title: "DACSS758 Text as Data Fall 2023"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - Tutorial1.qmd
      - Tutorial2.qmd
      - Tutorial3.qmd
      - Tutorial4.qmd
      - Tutorial5.qmd


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



